// import nessecary packages
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:intl/intl.dart';
part 'railway.g.dart';

@JsonSerializable() // This class is serializable to JSON
class JsonLatLng {
  // Json LatLng class to serialize and deserialize LatLng objects
  final double lat;
  final double lng;

  JsonLatLng(this.lat, this.lng);

  factory JsonLatLng.fromJson(
          Map<String, dynamic> json) => // Deserialize from JSON
      _$JsonLatLngFromJson(json);

  Map<String, dynamic> toJson() =>
      _$JsonLatLngToJson(this); // Serialize to JSON
}

@JsonSerializable()
class JsonColor {
  // Json Color class to serialize and deserialize Color objects
  int r, g, b;
  JsonColor(this.r, this.g, this.b);

  factory JsonColor.fromJson(
          Map<String, dynamic> json) => // Deserialize from JSON
      _$JsonColorFromJson(json);

  Map<String, dynamic> toJson() => _$JsonColorToJson(this); // Serialize to JSON

  Color toColor() => Color.fromARGB(255, r, g, b); // Convert to Color object

  JsonColor.fromColor(Color color) // Convert from Color object
      : r = color.red,
        g = color.green,
        b = color.blue;
}

DateFormat dateFormat = DateFormat('dd-MM-yyy'); // Date format for default name
DateFormat timeFormat = DateFormat('HH:mm'); // Time format for default name

@JsonSerializable()
class Railway {
  // Railway class to serialize and deserialize Railway objects
  // Initialize variables
  List<JsonLatLng> points = [];
  String name = "";
  String description = "";
  DateTime dateTime = DateTime.now();
  JsonColor color = JsonColor.fromColor(const Color(0xFFFF0000));

  Railway(this.color) {
    // Constructor
    name =
        "Railway journey on the ${dateFormat.format(DateTime.now())} at ${timeFormat.format(DateTime.now())}";
    dateTime = DateTime.now();
  }

  factory Railway.fromJson(Map<String, dynamic> json) =>
      _$RailwayFromJson(json);

  Map<String, dynamic> toJson() => _$RailwayToJson(this);
}

// Json serialisation code for other Objects in Autogenerated railway.g.dart